### ISSUE TITLE
Install / Start

### ISSUE THREAD

**Issue by BartManX** [zdzieblowski/foundation-v2-frontend#1]
how to install start and run ??

**Comment by zdzieblowski** [comment]
Hi, sorry - I just started work on this project - it's at most an API connection test at this point. Instructions on how to run it will be available as soon as there's a version worth running :)

**Comment by zdzieblowski** [comment]
I've finished with a sort of alpha and am testing it here: https://themining.site/EVR/

Documentation and upgraded configuration etc. coming soon :)
